version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: ${FLASK_ENV}
      DATABASE_URL: postgresql://postgres:examplepassword@db/stocktalk_db
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: stocktalk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
